### ISSUE TITLE
User Interface woes

### ISSUE THREAD

**Issue by LaughingBarista** [ofHillsAndLakes/Daemon-Souls#19] opened 2016-06-07 05:20 UTC
I've pushed the code I have for the beginning menu User Interface. It looks alright, though it's unfinished. I have been racking my brain against a few problems though:
- Trying to escape the menu and resume play been very unsuccessful
-  Every time I try to instantiate the player with these options, I get compile errors due to information not being set up.

I've tried:
- [x] Setting up a global Player testPlayer that could be made into a new object of type Barbarian, etc through the UI.
- [x] Switching the order through which variables were declared, etc. All to no avail.
- [x] .... many many things. Sometimes the same things over again because I hadn't remembered I'd already tried that. I'm not getting anywhere. I'll repost where I'm at with it, commented out.

If you guys have any ideas that would be lovely.
- [x]

**Comment by golbette** [comment] 2016-06-07 06:27
Can you put some sample code that's not working on a branch so we can take a look? Not sure what I actually need to do with your UI class to make it work as intended. I've tried messing with your UI class but all I've succeeded in is causing the game to hang indefinitely on a black screen. 

As for a menu, it should be easy to set up a flag in the main game loop that checks if you're in a menu once you press esc to summon up the menu or w/e, and freezes all other input handling if you are. 

You'll want to talk to Robert about the oddities in player typing. You can't call a Wizard's abilities on a player, and you can't instantiate a Wizard as a Barbarian, period, so that's dependent on his object accommodating a need for generics. My guess is that the direct call to Wizard functions is just debug code and can be commented out though. 

EDIT: I checked all the tickboxes you left because it felt satisfying and filled up a meter on the issue tracker.

**Comment by LaughingBarista** [comment] 2016-06-07 19:00
I'm glad that you enjoyed the tick boxes. I've made the appropriate branch for solving UI problems. My hope is that the issues will be a little clearer to see now.

**Comment by golbette** [comment] 2016-06-07 21:47
Does this run at all on your end? I can't get it to no matter how I configure libgdx, it just throws missing asset errors.

**Comment by LaughingBarista** [comment] 2016-06-07 21:55
Yes. That's odd that it throws that error. Can you post a screen shot?

**Comment by golbette** [comment] 2016-06-07 22:02
NVM, I'm a clown. I got it to work. LOADING EXCITEMENT

**Comment by RobertBohlman** [comment] 2016-06-07 22:06
Should I just wait to throw together the log until after you guys have this stuff pushed?

**Comment by golbette** [comment] 2016-06-07 22:09
I will be done and processing a push request on this fix in about an hour if you can handle the wait. There will be a UI skin asset you can use in the push once it's there (it's probably already there but might not be fully functional? not sure)

**Comment by LaughingBarista** [comment] 2016-06-07 22:10
Hah. I'll race you there then, Sam!

**Comment by RobertBohlman** [comment] 2016-06-07 22:11
It looks like all I need is a working skin and everything _should_ be simple after that.

**Comment by LaughingBarista** [comment] 2016-06-07 22:26
Curiously, is it possible to change the way the game runs to call render() before create()? If so many player class problems could be fixed through simple manipulation.

**Comment by golbette** [comment] 2016-06-07 22:27
Absolutely not, that's just how libgdx works.

Don't touch anything! I've almost got your code fixed and don't want merge conflicts.

**Comment by golbette** [comment] 2016-06-07 22:39
It's up. Everything works except your asset assignments, I'm not sure what you did there but even when I assign the player the correct class based on menu choice it doesn't change from the default yellow duck knight...person...thing. It looks like the assets are being loaded, but not assigned to the actual player object.

**Comment by LaughingBarista** [comment] 2016-06-07 22:45
Okay. Thanks Sam! I'll see what's going on, as well as how you fixed this problem.

**Comment by golbette** [comment] 2016-06-07 22:49
Found the problem with sprite selection and am fixing it now, it's a silly thing.

**Comment by golbette** [comment] 2016-06-07 22:55
Merged and pushed with your stuff. Make a Pull Request (and automerge if you can) once you're happy with what you've got on the player menu. (Hopefully soon, Robert needs it!)

**Comment by LaughingBarista** [comment] 2016-06-07 22:55
You have got to be kidding me. I've tried so many things to fix that. But the problem I always run into is using a Player testPlayer doesn't allow the proper instantiation of other variables in the create() method, even if we successfully instantiate the testPlayer to the appropriate type in the render() method.

**Comment by golbette** [comment] 2016-06-07 22:56
Don't sweat it. It turns out the assets being referenced were in the Sprites class, which don't update when the Assets class updates. When we pull them directly from assets.player_whatever all the Sprites are correct :+1:

**Comment by golbette** [comment] 2016-06-07 23:02
I'm going to go ahead and do the pull request since the codebase seems stable.

**Comment by LaughingBarista** [comment] 2016-06-07 23:02
You were able to get it to run accordingly? The error I get is the following:

![capture](https://cloud.githubusercontent.com/assets/15771896/15877513/2cc677a8-2cc9-11e6-94ba-7412968e2b90.PNG)

**Comment by LaughingBarista** [comment] 2016-06-07 23:10
Never mind. I refreshed the project from your pull and it works just fine. Well done. Thanks so much Sam!

**Comment by RobertBohlman** [comment] 2016-06-07 23:28
Alright well I just synced up and now that I've tried running it it seems the selection screen in the beginning is cut in half, and hitting the "Let's play" button doesn't seem to do anything.

**Comment by RobertBohlman** [comment] 2016-06-07 23:32
Okay, I think double clicking let the game start but the screen is still cut in half.

Edit: Or not. I can't get it to start again, I think what happened the first time is I managed to hit one of the buttons I couldn't see.

Edit: Well to make matters worse, it seems that using the skin from the UI class just causes a crash because it doesn't have all the required info for a textField. Honestly I'm at a bit of a loss for what to do.

**Comment by LaughingBarista** [comment] 2016-06-07 23:46
Oh don't worry about the UI class! Everything that will still be displayed while in-game I am putting into HUD. That way I can just figure out how to draw the hudStage over the game and not break things.. My current attempts break all ranged abilities, but I'll continue trying.

**Comment by LaughingBarista** [comment] 2016-06-07 23:46
For the start screen, feel free to give a screen shot.

**Comment by RobertBohlman** [comment] 2016-06-07 23:48
My second edit was referring to me not knowing what to do for the combat log. I mean, I _guess_ I could fake it by just drawing text on a rectangle and setting the timers hopefully slow enough that people can read them line by line. But I'd rather not.

**Comment by LaughingBarista** [comment] 2016-06-07 23:53
Yes I understood that. I'm trying to get the hud to draw nicely so that we can both test it as we write the hud. Basically, in the HUD class, we need to make a configuration for whatever kind of  'actor' we plan on adding. Then we add that 'style' to the skin. When we instantiate that actor, whether it be a textButton or whatever, it has to have a style set in the constructor that we pull from the skin. Once satisfied with the actor, we add it to the table, which is in turn added to the stage. Does that help at all? :/

**Comment by RobertBohlman** [comment] 2016-06-07 23:55
Um, kind of. Though I have no idea how I would do that.

**Comment by LaughingBarista** [comment] 2016-06-08 00:05
I tried to set the UI class up in a way that would be somewhat understandable. Have you looked at it for reference? I can also post the links that I learned from if that would help.

**Comment by RobertBohlman** [comment] 2016-06-08 00:13
The problem is the skin doesn't seem to work with the TextField

![image](https://cloud.githubusercontent.com/assets/12433391/15878839/1f728be6-2cd3-11e6-8777-d7b09155a41f.png)

**Comment by LaughingBarista** [comment] 2016-06-08 00:25
Hmmm.. try it like this:

![capture](https://cloud.githubusercontent.com/assets/15771896/15878983/c296abf8-2cd4-11e6-8633-1562bb261944.PNG)

**Comment by RobertBohlman** [comment] 2016-06-08 00:38
Okay well it didn't crash, but I also can't see if it did anything :/.

**Comment by LaughingBarista** [comment] 2016-06-08 00:39
Yeah I'm working on that. Here I'll provide a small fix so that you can, just know that it breaks combat.

**Comment by LaughingBarista** [comment] 2016-06-08 00:54
Here, see for yourself. I'll upload it to a separate branch so as to not destroy anything.

**Closed as completed** 2016-06-08 20:41 UTC
